---
image: docker:stable

variables:
  # https://about.gitlab.com/blog/2019/07/31/docker-in-docker-with-docker-19-dot-03/
  DOCKER_DRIVER: overlay2
  # Create the certificates inside this directory for both the server
  # and client. The certificates used by the client will be created in
  # /certs/client so we only need to share this directory with the
  # volume mount in `config.toml`.
  DOCKER_TLS_CERTDIR: "/certs"

services:
  - docker:dind

stages:
  - build
  - push
  - test

before_script:
  - docker info

build_d9:
  stage: build
  script:
    # https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
    - docker build --rm -f Dockerfile-debian9 -t $CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:9 -t $CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:stretch .
    - docker build --rm -f Dockerfile-debian10 -t $CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:10 -t $CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:buster .

push_d9_to_gitlab:
 stage: push
 only:
   - master
 script:
   - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" "$CI_REGISTRY" --password-stdin
   - docker build --rm -f Dockerfile-debian9 -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:9 -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:stretch -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:9 -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:stretch .
   - docker build --rm -f Dockerfile-debian10 -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:10 -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:buster -t $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:latest -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:10 -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:buster -t $DOCKERHUB_USER/$DOCKERHUB_PROJECT:latest .
   - docker images
   - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:9
   - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:stretch
   - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:10
   - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:buster
   - docker push $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:latest
   - echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USER" --password-stdin
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:9
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:stretch
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:10
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:buster
   - docker push $DOCKERHUB_USER/$DOCKERHUB_PROJECT:latest

test_docker_images:
  stage: test
  only:
   - master
  script:
    - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:stretch cat /etc/apt/sources.list
    - docker run --rm $DOCKERHUB_USER/$DOCKERHUB_PROJECT:buster cat /etc/apt/sources.list
    - docker run --rm $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:stretch cat /etc/apt/sources.list
    - docker run --rm $CI_REGISTRY/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:buster cat /etc/apt/sources.list