---
image: docker:stable

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  # https://gitlab.com/gitlab-org/gitlab-ce/issues/64959
  # 19.03 had some breaking changes compared to 18.09
  DOCKER_TLS_CERTDIR: ""

services:
  - docker:dind

stages:
  - build
  - push

before_script:
  - docker info
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD

build_d9:
  stage: build
  script:
    # https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
    - docker build --rm -f Dockerfile-debian9 -t $CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:9 -t $CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:stretch .

build_d10:
  stage: build
  script:
    # https://docs.gitlab.com/ee/ci/variables/predefined_variables.html
    - docker build --rm -f Dockerfile-debian10 -t $CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:10 -t $CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:buster .

push_d9:
 stage: push
 only:
   - master
 script:
   - docker build --rm -f Dockerfile-debian9 -t $CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:9 -t $CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:stretch .
   - docker images
   - docker push $CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:9
   - docker push $CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:stretch

push_d10:
 stage: push
 only:
   - master
 script:
   - docker build --rm -f Dockerfile-debian10 -t $CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:10 -t $CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:buster -t $CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:latest .
   - docker images
   - docker push $CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:10
   - docker push $CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:buster
   - docker push $CI_REGISTRY_USER/$CI_REGISTRY_IMAGE:latest